app_pages:
    resource: "@AppBundle/Resources/config/routing/pages.yml"
    prefix:   /pages

app_contact:
    resource: "@AppBundle/Resources/config/routing/contact.yml"
    prefix:   /contact

app_gallery:
    resource: "@AppBundle/Resources/config/routing/gallery.yml"
    prefix:   /gallery

app_images:
    resource: "@AppBundle/Resources/config/routing/images.yml"
    prefix:   /images

app_packages:
    resource: "@AppBundle/Resources/config/routing/packages.yml"
    prefix:   /packages

app_reviews:
    resource: "@AppBundle/Resources/config/routing/reviews.yml"
    prefix:   /reviews

tea_homestay_booking:
    path: /booking
    defaults: {_controller: AppBundle:Booking:contact }

tea_homestay_pageview:
    path: /page/{id}
    defaults: {_controller: AppBundle:Front:PageView }


tea_homestay_packageview:
    path: /packages/{id}
    defaults: {_controller: AppBundle:Front:PackageView }


tea_homestay_galleryview:
    path: /photo/gallery
    defaults: {_controller: AppBundle:Front:GalleryShow}


tea_homestay_contact:
    path: /contact_show/{id}
    defaults: {_controller: AppBundle:Front:Contact}
